project_name: alveychain

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./main.go
    binary: alveychain
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      -s -w -X 'github.com/alveycoin/alveychain/versioning.Version=v{{ .Version }}'

  - id: darwin-arm64
    main: ./main.go
    binary: alveychain
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      -s -w -X 'github.com/alveycoin/alveychain/versioning.Version=v{{ .Version }}'

  - id: linux-amd64
    main: ./main.go
    binary: alveychain
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/alveycoin/alveychain/versioning.Version=v{{ .Version }}'
    tags:
      - netgo

  - id: linux-arm64
    main: ./main.go
    binary: alveychain
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -linkmode external -extldflags "-static" -X 'github.com/alveycoin/alveychain/versioning.Version=v{{ .Version }}'
    tags:
      - netgo

archives:
  -
    files:
      - LICENSE
      - README.md

#nfpms:
#  - vendor: AlveyCoin
#    homepage: https://alveychain.com
#    maintainer: Alvey Coin Team <edge@alveychain.com>
#    description:  A Framework for Building Ethereum-compatible Blockchain Networks
#    license: GPLv3 LGPLv3
#
#    formats:
#      - apk
#      - deb
#      - rpm
#
#    contents:
#      - src: alveychain.service
#        dst: /lib/systemd/system/alveychain.service
#        type: config
#
#    overrides:
#      rpm:
#        replacements:
#          amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: false

  - image_templates:
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64
    skip_push: false

docker_manifests:
  - name_template: AlveyCoin/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-amd64
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false

  - name_template: AlveyCoin/{{ .ProjectName }}:latest
    image_templates:
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-amd64
      - AlveyCoin/{{ .ProjectName }}:{{ .Version }}-arm64
    skip_push: false
